import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { saveAs } from 'file-saver'; // File saving utility

@Component({
  selector: 'app-mapping',
  templateUrl: './mapping.component.html',
  styleUrls: ['./mapping.component.css']
})
export class MappingComponent implements OnInit {
  sourceData: any[] = []; // Data from the SWIFT message
  mappings: any[] = []; // Mappings generated by AI
  isLoading: boolean = false; // Loading state

  constructor(private http: HttpClient) {}

  ngOnInit() {
    // Fetch source data (from the uploaded SWIFT message)
    this.http.get('/api/extract').subscribe((data: any) => {
      this.sourceData = data;
    });
  }

  generateMappings() {
    this.isLoading = true; // Show loading indicator
    // Call AI API to generate mappings
    this.http.post('/ai/mapping', this.sourceData).subscribe(
      (response: any) => {
        this.mappings = response.mappings;
        this.isLoading = false; // Hide loading indicator
      },
      (error) => {
        console.error('Error generating mappings', error);
        this.isLoading = false; // Hide loading indicator
      }
    );
  }

  saveMappings() {
    this.http.post('/api/save', this.mappings).subscribe(() => {
      console.log('Mappings saved successfully');
    });
  }

  downloadMappings() {
    const fileBlob = new Blob([JSON.stringify(this.mappings)], { type: 'application/json' });
    saveAs(fileBlob, 'mappings.json'); // Trigger download
  }
}
